apiVersion: v1
kind: Pod
metadata:
  name: pod-dynamic-pv-test-2
  namespace: lab
  labels:
    app: pod-dynamic-pv-test
spec:
  containers:
    - name: app
      image: alpine:3.20
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: dados
          mountPath: /data
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "250m"
          memory: "256Mi"
  volumes:
    - name: dados
      persistentVolumeClaim:
        claimName: app-data
