apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-data
  namespace: lab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: pd-balanced-retain
  resources:
    requests:
      storage: 10Gi
