apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pd-balanced-retain
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-balanced
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
