apiVersion: v1
kind: Pod
metadata:
  name: postgres
  namespace: lab
  labels:
    app: postgres
spec:
  containers:
    - name: postgres
      image: postgres:16
      ports:
        - containerPort: 5432
          name: postgres
      env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: app-postgres-config
              key: DB_NAME
        - name: PGDATA
          valueFrom:
            configMapKeyRef:
              name: app-postgres-config
              key: PGDATA
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: app-postgres-secret
              key: DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-postgres-secret
              key: DB_PASSWORD
      volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      readinessProbe:
        tcpSocket:
          port: 5432
        initialDelaySeconds: 10
        periodSeconds: 5
      livenessProbe:
        tcpSocket:
          port: 5432
        initialDelaySeconds: 20
        periodSeconds: 10
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "250m"
          memory: "256Mi"
  volumes:
    - name: postgres-data
      emptyDir: {}
