apiVersion: v1
kind: Pod
metadata:
  name: postgres-client
  namespace: lab
  labels:
    app: postgres-client
spec:
  restartPolicy: Always
  containers:
    - name: postgres-client
      image: postgres:16
      command: ["sh", "-c", "sleep infinity"]
      envFrom:
        - configMapRef:
            name: app-postgres-config
        - secretRef:
            name: app-postgres-secret
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "250m"
          memory: "256Mi"
