apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
  namespace: lab
  labels:
    app: ubuntu
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu:24.04
      command: ["bash", "-lc", "sleep infinity"]
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "250m"
          memory: "256Mi"