apiVersion: v1
kind: Pod
metadata:
  name: portal-noticias
  namespace: lab
  labels:
    app: portal-noticias
spec:
  containers:
    - name: alura
      image: aluracursos/portal-noticias:1
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "250m"
          memory: "256Mi"
